/// <reference types="node" />
import { jest, describe, it, expect, beforeEach, afterEach } from '@jest/globals';

// Define the mock before any imports
const mockHash = jest.fn();
const mockVerify = jest.fn();

// Argon2id constant value
const ARGON2ID = 2;

jest.unstable_mockModule('argon2', () => ({
  argon2id: ARGON2ID,
  hash: mockHash,
  verify: mockVerify,
  default: {
    argon2id: ARGON2ID,
    hash: mockHash,
    verify: mockVerify,
  }
}));

/**
 * Unit tests for hash utilities.
 */
describe('Hash Utils Unit Tests', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    jest.resetModules();
    process.env = { ...originalEnv };
    mockHash.mockClear();
    mockVerify.mockClear();
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  describe('gerarHash', () => {
    it('should generate a hash with default parameters when env vars are missing', async () => {
      const { gerarHash } = await import('../../../src/utils/hash');
      
      const password = 'test-password';
      mockHash.mockResolvedValue('mocked-hash');
      
      await gerarHash(password);

      expect(mockHash).toHaveBeenCalledWith(password, expect.objectContaining({
        memoryCost: 8192,
        timeCost: 2,
        parallelism: 1,
        type: ARGON2ID
      }));
    });

    it('should generate a hash with custom parameters from env vars', async () => {
      process.env.ARGON2_MEMORY_COST = '16384';
      process.env.ARGON2_TIME_COST = '4';
      process.env.ARGON2_PARALLELISM = '2';

      const { gerarHash } = await import('../../../src/utils/hash');
      
      const password = 'test-password';
      mockHash.mockResolvedValue('mocked-hash');
      
      await gerarHash(password);

      expect(mockHash).toHaveBeenCalledWith(password, expect.objectContaining({
        memoryCost: 16384,
        timeCost: 4,
        parallelism: 2
      }));
    });

    it('should return the hash generated by argon2', async () => {
      const { gerarHash } = await import('../../../src/utils/hash');
      const password = 'test-password';
      mockHash.mockResolvedValue('$argon2id$mocked-hash');
      
      const result = await gerarHash(password);
      
      expect(result).toBe('$argon2id$mocked-hash');
    });
  });

  describe('verificarHash', () => {
    it('should return true when argon2.verify returns true', async () => {
      const { verificarHash } = await import('../../../src/utils/hash');
      const password = 'correct-password';
      const hash = 'some-hash';
      
      mockVerify.mockResolvedValue(true);
      
      const result = await verificarHash(hash, password);
      
      expect(result).toBe(true);
      expect(mockVerify).toHaveBeenCalledWith(hash, password);
    });

    it('should return false when argon2.verify returns false', async () => {
      const { verificarHash } = await import('../../../src/utils/hash');
      const password = 'wrong-password';
      const hash = 'some-hash';
      
      mockVerify.mockResolvedValue(false);
      
      const result = await verificarHash(hash, password);
      
      expect(result).toBe(false);
      expect(mockVerify).toHaveBeenCalledWith(hash, password);
    });
  });
});

